version: '3.8'

volumes:
  prometheus_data: {}

services:

  kong:
    image: kong:2.8.1-ubuntu
    platform: linux/arm64
    volumes:
      - ../holajobs-config/kong:/etc/kong/
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /etc/kong/kong.yml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_ADMIN_GUI_URL: http://localhost:8002
    ports:
      - 8000:8000
      - 8001:8001

  prometheus:
    image: prom/prometheus:v2.32.1
    platform: linux/arm64
    volumes:
      - ../holajobs-config/prometheus:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
    ports:
      - 9090:9090
   
  mongo:
    image: mongo
    platform: linux/arm64
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - "../holajobs-config/mongo/mongo-entrypoints/:/docker-entrypoint-initdb.d/"
    ports:
      - 27017:27017
    
  user-manager:
    build: .
    platform: linux/arm64
    env_file: 
      ../holajobs-config/user-manager/development.properties
    ports:
      - 3000:3000
    depends_on: 
      - mongo
      - prometheus
      - kong